<template>
  <v-container
    class="tw-h-screen"
  >
    <v-row
      class="tw-h-full"
    >
      <v-col
        cols="12"
        md="6"
      >
        <v-row
          justify="center"
          align="center"
          class="tw-h-full"
        >
          <div>
            <h1
              class="tw-text-6xl"
            >
              SpaceChat
            </h1>
            <span
              class="tw-text-lg"
            >
              Chat with your friends, find new friends
            </span>
          </div>
        </v-row>
      </v-col>
      <v-col
        cols="12"
        md="6"
      >
        <v-row
          justify="center"
          align="center"
          class="tw-h-full"
        >
          <v-col
            cols="12"
            md="10"
          >
            <v-card
              class="tw-p-2"
            >
              <router-view></router-view>
            </v-card>
          </v-col>
        </v-row>
      </v-col>
    </v-row>
  </v-container>
</template>
